apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: akashnewscapepune/productimg:latest
          ports:
            - containerPort: 9700		
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  ports:
    - nodePort: 30273
      port: 9700
      targetPort: 9700
      protocol: TCP
  selector:
    app: product
  type: NodePort
